import React, { useState, useRef, useEffect } from 'react';

interface ExportMenuProps {
  content: string;
  title?: string;
  severity?: string;
}

export function ExportMenu({ content, title = 'KubeSignal Report', severity }: ExportMenuProps) {
  const [isOpen, setIsOpen] = useState(false);
  const [copied, setCopied] = useState(false);
  const menuRef = useRef<HTMLDivElement>(null);

  // Close on outside click
  useEffect(() => {
    if (!isOpen) return;
    const handler = (e: MouseEvent) => {
      if (menuRef.current && !menuRef.current.contains(e.target as Node)) {
        setIsOpen(false);
      }
    };
    document.addEventListener('mousedown', handler);
    return () => document.removeEventListener('mousedown', handler);
  }, [isOpen]);

  const toMarkdown = (): string => {
    const lines = [`# ${title}`, ''];
    if (severity) {
      lines.push(`**Severity:** ${severity}`, '');
    }
    lines.push(`**Generated:** ${new Date().toLocaleString()}`, '');
    lines.push('---', '');
    lines.push(content);
    lines.push('', '---', '*Generated by KubeSignal*');
    return lines.join('\n');
  };

  const handleCopyMarkdown = async () => {
    const md = toMarkdown();
    try {
      await navigator.clipboard.writeText(md);
    } catch {
      const textarea = document.createElement('textarea');
      textarea.value = md;
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand('copy');
      document.body.removeChild(textarea);
    }
    setCopied(true);
    setTimeout(() => { setCopied(false); setIsOpen(false); }, 1500);
  };

  const handleDownloadTxt = () => {
    const md = toMarkdown();
    const blob = new Blob([md], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${title.replace(/[^a-zA-Z0-9]/g, '_').toLowerCase()}_${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    setIsOpen(false);
  };

  const handlePrintPDF = () => {
    // Create a print-friendly container
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;

    const severityColor =
      severity === 'P0' ? '#ef4444'
      : severity === 'P1' ? '#f97316'
      : severity === 'P2' ? '#eab308'
      : severity === 'P3' ? '#22c55e'
      : severity === 'P4' ? '#3b82f6'
      : '#6b7280';

    const html = `<!DOCTYPE html>
<html>
<head>
  <title>${title}</title>
  <style>
    @media print {
      @page { margin: 1.5cm; }
    }
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      color: #1a1a1a;
      line-height: 1.6;
      padding: 2rem;
      max-width: 800px;
      margin: 0 auto;
    }
    .report-header {
      border-bottom: 3px solid #326ce5;
      padding-bottom: 1rem;
      margin-bottom: 1.5rem;
    }
    .report-title {
      font-size: 1.5rem;
      font-weight: 700;
      color: #111;
      display: flex;
      align-items: center;
      gap: 0.75rem;
    }
    .report-logo {
      width: 32px;
      height: 32px;
      background: #326ce5;
      border-radius: 8px;
      display: flex;
      align-items: center;
      justify-content: center;
      color: white;
      font-weight: bold;
      font-size: 14px;
    }
    .report-meta {
      font-size: 0.85rem;
      color: #666;
      margin-top: 0.5rem;
    }
    .severity-badge {
      display: inline-block;
      padding: 0.2rem 0.75rem;
      border-radius: 9999px;
      font-size: 0.8rem;
      font-weight: 700;
      color: white;
      background: ${severityColor};
      margin-right: 0.5rem;
    }
    .report-body {
      white-space: pre-wrap;
      font-size: 0.9rem;
    }
    .report-body h2, .report-body h3 {
      margin-top: 1.25rem;
      margin-bottom: 0.5rem;
      color: #326ce5;
    }
    .report-footer {
      border-top: 1px solid #e5e7eb;
      margin-top: 2rem;
      padding-top: 1rem;
      font-size: 0.75rem;
      color: #999;
      text-align: center;
    }
    code {
      background: #f3f4f6;
      padding: 0.15rem 0.4rem;
      border-radius: 4px;
      font-family: 'SF Mono', monospace;
      font-size: 0.85em;
    }
    pre {
      background: #f3f4f6;
      padding: 1rem;
      border-radius: 8px;
      overflow-x: auto;
      margin: 0.75rem 0;
    }
  </style>
</head>
<body>
  <div class="report-header">
    <div class="report-title">
      <div class="report-logo">AL</div>
      KubeSignal Report
    </div>
    <div class="report-meta">
      ${severity ? `<span class="severity-badge">${severity}</span>` : ''}
      Generated on ${new Date().toLocaleString()}
    </div>
  </div>
  <div class="report-body">${escapeHtml(content)}</div>
  <div class="report-footer">Generated by KubeSignal &mdash; AI-powered Kubernetes Alert Analysis</div>
  <script>window.onload = function() { window.print(); }</script>
</body>
</html>`;

    printWindow.document.write(html);
    printWindow.document.close();
    setIsOpen(false);
  };

  return (
    <div ref={menuRef} className="relative inline-block">
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="btn-secondary text-xs flex items-center gap-1.5"
        title="Export results"
      >
        <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
        </svg>
        Export
      </button>

      {isOpen && (
        <div className="export-menu">
          <button
            className="export-menu-item"
            onClick={handleCopyMarkdown}
          >
            <svg className="w-4 h-4 text-k8s-accent" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
            </svg>
            <div className="flex-1 text-left">
              <div className="text-xs font-medium text-k8s-text">
                {copied ? 'Copied!' : 'Copy Markdown'}
              </div>
              <div className="text-[10px] text-k8s-muted">Formatted with headers</div>
            </div>
          </button>

          <button
            className="export-menu-item"
            onClick={handleDownloadTxt}
          >
            <svg className="w-4 h-4 text-green-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
            </svg>
            <div className="flex-1 text-left">
              <div className="text-xs font-medium text-k8s-text">Download .txt</div>
              <div className="text-[10px] text-k8s-muted">Save as text file</div>
            </div>
          </button>

          <button
            className="export-menu-item"
            onClick={handlePrintPDF}
          >
            <svg className="w-4 h-4 text-purple-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z" />
            </svg>
            <div className="flex-1 text-left">
              <div className="text-xs font-medium text-k8s-text">Print PDF</div>
              <div className="text-[10px] text-k8s-muted">Print-ready report</div>
            </div>
          </button>
        </div>
      )}
    </div>
  );
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
